### ISSUE TITLE
Crafting mishap

### ISSUE THREAD

**Issue by daviddoodles** [TheOnlySilverClaw/Reforged#177] opened 2017-10-26 11:32 UTC
there is some problem relating about the fact that some crafting recipes dont match the one like the wooden weapons

they use LOGS instead of planks

**Comment by ThexXTURBOXx** [comment] 2017-10-26 22:00
Do you mean the Mace for instance? If yes, this is intended behavior

**Comment by ThexXTURBOXx** [comment] 2022-09-03 14:00
I am still unsure about this issue, sadly. Closing this until further context is provided

**Closed as completed by ThexXTURBOXx** 2022-09-03 14:00 UTC
