### ISSUE TITLE
Enchanting bug

### ISSUE THREAD

**Issue by elreden** [TheOnlySilverClaw/Reforged#157] opened 2017-05-25 09:03 UTC
I've discovered an issue where in it is possible to enchant the weapons added by the game but the moment the player attacks any sort of mob with an enchanted weapon it crashes the game

**Comment by ThexXTURBOXx** [comment] 2017-05-25 09:31
Thanks for reporting, I will take a look at this :)

**Comment by ThexXTURBOXx** [comment] 2017-05-25 09:36
I can enchant them, but I cannot reproduce the crash. Could you send me the crashlog?

**Comment by elreden** [comment] 2017-05-26 01:02
this should be it

[crash-2017-05-25_03.57.52-client.txt](https://github.com/ThexXTURBOXx/Reforged/files/1030537/crash-2017-05-25_03.57.52-client.txt)

**Comment by ThexXTURBOXx** [comment] 2017-05-26 12:17
I will take a look at this, thanks for reporting :)

**Comment by ThexXTURBOXx** [comment] 2017-05-26 18:12
Fixed in next version :)

**Closed as completed** 2017-05-26 18:12 UTC
Labels: bug
