### ISSUE TITLE
A lot of weapons do not render properly when held

### ISSUE THREAD

**Issue by Sunconure11** [TheOnlySilverClaw/Reforged#158] opened 2017-05-25 12:37 UTC

**Comment by ThexXTURBOXx** [comment] 2017-05-25 12:39
Do you mean the pixel-bug again or do you mean, that they aren't transformed the right way?
I didn't transform the left hand yet (I don't support it right now, this will come later on)

**Comment by Sunconure11** [comment] 2017-05-25 12:45
Crossbows do not have proper rendering when held in the main hand, as with the nest of bees.

Also, crossbows cannot be fired in creative.

**Comment by ThexXTURBOXx** [comment] 2017-05-25 14:20
Which Minecraft version are you using?

**Comment by Sunconure11** [comment] 2017-05-25 14:24
1.11.2 - 13.20.0.2304

**Comment by ThexXTURBOXx** [comment] 2017-05-25 19:52
![2017-05-25_21 50 34](https://cloud.githubusercontent.com/assets/12763829/26467816/70cc0be4-4194-11e7-9b79-31fa26e5ceae.png)
![2017-05-25_21 50 42](https://cloud.githubusercontent.com/assets/12763829/26467814/70c7aefa-4194-11e7-9ebd-c2b05ab1feec.png)
![2017-05-25_21 50 46](https://cloud.githubusercontent.com/assets/12763829/26467815/70cb03ac-4194-11e7-8647-7f830a89a575.png)

That's odd, for me everything works fine... Did you accidently use the deobf-version?

**Comment by Sunconure11** [comment] 2017-05-25 20:06
I used the build provided on curseforge. Strange.

**Comment by ThexXTURBOXx** [comment] 2017-05-25 21:16
Could you try again and look? :D If the issue isn't there anymore, I close this one :)

**Comment by Sunconure11** [comment] 2017-05-25 21:27
I'll check in a bit, I'm trying to fix some things with my own mod, ironically. Porting straight from 1.10.2 to 1.11.2 caused some hiccups.

**Comment by ThexXTURBOXx** [comment] 2017-05-25 22:10
Take your time :) Good luck tho ^^

**Comment by Sunconure11** [comment] 2017-05-31 19:58
It looks like they can be fired again in creative and what not, but some of the first person animations for reloading stuff is off in general.

**Comment by ThexXTURBOXx** [comment] 2017-06-01 00:01
Okay, yeah. I know about that issue, but it is nearly impossible to fix, because the item transform helper can't transform my reloading stuff... :/
Maybe later on, when it works. :)

**Closed as completed by ThexXTURBOXx** 2017-06-01 00:01 UTC
Labels: bug
